services:
  app:
    build:
      dockerfile: .docker/php/Dockerfile
      target: prod
    container_name: horangi-work-schedule-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - app_code:/var/www
      - ./code/storage:/var/www/storage
    environment:
      APP_ENV: production
      APP_DEBUG: false
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: horangi-work-schedule-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - app_code:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: horangi-work-schedule-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
    # porta NON esposta all'host in produzione
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 5
      timeout: 5s
      interval: 10s
      start_period: 30s
    user: mysql

volumes:
  app_code:
  db_data:
